stackrox/infra

chart/infra-server/Chart.yaml
Bumping demo versions for ACS release 4.2.0
=> Bump demo versions to 4.2.0

scripts/cost-estimation/render_costs.py
Unsorted: https://github.com/stackrox/infra/actions/runs/6219457797
Sorted: https://github.com/stackrox/infra/actions/runs/6219664162
=> fix(cost report): sort flavors alphabetically for more consistent output

.github/workflows/build-and-push.yaml, certifier/Dockerfile, certifier/Makefile, certifier/main.go, chart/infra-server/templates/demo-certifier.yaml
Arguably, this is not the right location for this CronJob. But this is Hackathon.
=> Add certifier for *.internal-registry.ci.rox.systems

chart/infra-server/Chart.yaml
Bumping demo versions for ACS release 4.2.1
=> Bump demo versions to 4.2.1

ui/src/containers/HomePage/HomePage.tsx, ui/src/infra.css
=> Remove padding from bottom panel

ui/src/components/PageSection.tsx
Reverts stackrox/infra#1036 which broke scroll on the log page.
=> Revert "PatternFly the PageSection component"

chart/infra-server/Chart.yaml
Bumping demo versions for ACS release 4.3.0
=> Bump demo versions to 4.3.0

.github/workflows/PR.yaml, .github/workflows/build-and-push.yaml
Per title. The secret was added as a dependabot and action secret to the repo via the org secret.
The image is built :heavy_check_mark:  and the comment is added to the PR :heavy_check_mark:
=> chore(ci): switch to rhacs-bot

DEPLOYMENT.md
Make it more clear how to tag a new version and rollback.
=> chore: update deployment notes

CHANGELOG.md, chart/infra-server/static/workflow-demo.yaml, chart/infra-server/static/workflow-openshift-4-demo.yaml, chart/infra-server/static/workflow-qa-demo.yaml
https://github.com/stackrox/automation-flavors/releases/tag/0.9.13
=> release: 0.9.13 demo flavors

chart/infra-server/static/workflow-openshift-ibmroks.yaml
Rollout (previously testing) for https://github.com/stackrox/automation-flavors/pull/190.
=> fix(ROX-22142): wait for nodes to be ready in IBM roks

CHANGELOG.md, chart/infra-server/static/workflow-openshift-4.yaml
Infra bump for https://github.com/stackrox/automation-flavors/pull/191.
=> ROX-21034: create workload identity pool for OCP

CHANGELOG.md, chart/infra-server/static/workflow-gke-default.yaml
Companion to https://github.com/stackrox/automation-flavors/pull/198
=> fix: Improve GKE deletion with retries

.github/workflows/deploy.yaml, .gitignore, DEPLOYMENT.md, scripts/deploy/helm.sh
Minor changes to use the resources created by https://github.com/stackrox/automation-iac/pull/59.
=> chore: move dev.infra to RH GCP

.github/workflows/smoke-test.yaml
This is a manually dispatched workflow that will attempt to create clusters in all flavors in the given infra PR cluster.
Split from #1203 .
Example run:  https://github.com/stackrox/infra/actions/runs/8156066579/job/22292895422
=> ROX-15590: implement smoke test for all flavors

scripts/local-dev/main.go, scripts/local-dev/prepare.sh
After #1203 , workflows need to be rendered.
=> fix: adapt the local-dev scripts to rendered workflow

service/cluster/cluster.go, service/metrics/metrics.go
Implements the following custom Prometheus metrics:
- Counter for flavors used
=> ROX-15587: Add basic Prometheus metrics

chart/infra-server/templates/monitoring/servicemonitors.yaml, chart/infra-server/templates/monitoring/services.yaml
=> ROX-15587: scrape infra-server metrics with a service monitor

.github/workflows/deploy.yaml
See https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0 for breaking changes.
Proof: 
* https://github.com/stackrox/infra/actions/runs/12809830973/job/35715505252
* https://redhat-internal.slack.com/archives/CVANK5K5W/p1737033902416659
=> fix: Slack message on deploy format changed

.github/workflows/auto-merge.yml
Well...
https://stackoverflow.com/questions/71481086/is-pull-request-label-available-to-a-github-action
=> fix(auto-merge): label selector needs to iterate names

.github/workflows/smoke-test.yaml, chart/infra-server/static/workflow-aks.yaml, chart/infra-server/static/workflow-eks.yaml
Follow up to https://github.com/stackrox/automation-flavors/pull/315, #1543
=> fix(eks, aks): add missing workflow data volume
