stackrox/infra

chart/infra-server/templates/deployment.yaml
chart/infra-server/templates/secrets.yaml

Infra PR GKE clusters run in RH GCP and need a pull secret to pull images from SR GCR.
Ultimately these images need to be pushed elsewhere: https://issues.redhat.com/browse/ROX-19827
Requires: https://github.com/stackrox/automation-iac/pull/16

Allow PRs to pull images

---

cmd/infractl/cluster/create/command.go
cmd/infractl/cluster/create/create.bats

This reverts commit 5128fa5b35755f96f782a6629851e5dd1e37c3cb.

Revert "ROX-19609: add cluster name validation to infractl (#980)"

---

chart/infra-server/static/flavors.yaml
chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-4-perf-scale.yaml
chart/infra-server/static/workflow-openshift-4.yaml

See https://github.com/stackrox/automation-flavors/pull/152.
I tested both ingress and api certificates successfully on a dev cluster I created with the new infra version.
The certificate creation is behind a feature flag (`trusted-certs-enabled`) with default false. If we don't observe any issues, we may switch the default to true later on.

ROX-17295: trusted certificates for openshift-4

---

ui/src/components/Modal.tsx
ui/src/containers/ClusterInfoPage/DeleteClusterModal.tsx
ui/src/containers/ClusterInfoPage/DownloadArtifactsModal.tsx

Fixes a warning from Modal.tsx introduced by #1001. 
Also reverts artifacts to the order set by flavors.yaml which is what we want:tm:. 
And uses danger as per #1001 review comment.

UI: Fix warning and sort and CSS from #1001

---

chart/infra-server/static/flavors.yaml
chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-4-perf-scale.yaml
chart/infra-server/static/workflow-openshift-4.yaml
chart/infra-server/static/workflow-openshift-aro.yaml
chart/infra-server/static/workflow-openshift-rosa.yaml
chart/infra-server/static/workflow-osd-aws.yaml
chart/infra-server/static/workflow-osd-gcp.yaml

It is somewhat annoying that these cluster flavors do not all expose the console connection parameters in artifacts. This PR makes them all consistently provide artifacts named:
- cluster-console-url
- cluster-console-username
- cluster-console-password
Existing other names are kept for any automation that depends on them e.g. kubeadmin-password. The change is relatively similar across flavors as all OCP 4 flavors create a `dotenv` artifact but they differ in the env name for the three values.

Use more consistent artifact naming for openshift clusters

---

chart/infra-server/static/workflow-osd-gcp.yaml

This change was tested with #1014 but missed that PR/commit.

Use public image for OSD-on-GCP flavor

---

CHANGELOG.md
cmd/infractl/cluster/create/command.go
ui/src/containers/LaunchClusterPage/ClusterForm.tsx
ui/src/utils/cluster.utils.ts

- Bug: https://issues.redhat.com/browse/ROX-15492 
- Fixed long time ago in https://github.com/stackrox/automation-flavors/pull/71 
- Validation “name” in OCP 3.11 flavor: https://github.com/stackrox/automation-flavors/blob/master/openshift/multi/terraform/main.tf#L43 
- Maximum allowed: 28 characters (<=28) to stay within 63 character limit for “openshift_public_hostname”
Question: Does this also affect other OCP versions?
- Input validation: https://github.com/stackrox/infra/blob/master/ui/src/containers/LaunchClusterPage/ClusterForm.tsx#L41-L48 
- Maximum length of 28 characters (<= 28, [Code](https://github.com/stackrox/infra/blob/master/ui/src/containers/LaunchClusterPage/ClusterForm.tsx#L44C12-L44C12))
- THAT SHOULD BE 27 characters (<= 28), because max is inclusive
- Regex allows …

fix: cluster name length should be maximum 28

---

chart/infra-server/static/flavors.yaml
chart/infra-server/static/workflow-aks.yaml
chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-4-perf-scale.yaml
chart/infra-server/static/workflow-openshift-4.yaml
chart/infra-server/static/workflow-osd-gcp.yaml
chart/infra-server/templates/openshift-4/secrets.yaml
chart/infra-server/templates/osd/secrets.yaml
ui/src/utils/cluster.utils.ts

Changes as described in: https://docs.google.com/document/d/1zFr2mUZVEZNofD5S1gj9ELSvwrKLnOe6aESm17D8IrI/edit?pli=1
IaC side: https://github.com/stackrox/automation-iac/pull/23
Created & destroyed:
Installed ACS:
Created with certs:
- secured cluster did not deploy due to a cert issue - will check if this is a bug in the existing setup
- this appears to be an existing timing bug. I will retest post deployment and open a JIRA.

ROX-19218, etc: Move GCP based OCP flavors in infra to a RH project

---

ui/src/components/PageSection.tsx

Replaces the custom stuff with a PatternFly Panel. The header is more padded on top/bottom but sticking with PatternFly look is the way to go :tm:

PatternFly the PageSection component

---

.github/workflows/PR.yaml
.github/workflows/deploy.yaml
CHANGELOG.md
DEPLOYMENT.md
Makefile
chart/infra-server/templates/argo/secrets.yaml

The `argo-workflows-workflow-controller-configmap` ConfigMap is originally created by the Argo Helm release. It is required to configure the artefact storage. 
When attempting to install the infra-server, Helm detects that this chart does not manage the ConfigMap and fails. 
This is a workaround until https://issues.redhat.com/browse/ROX-20269 is implemented.
Tested with the PR cluster that both installs on an empty cluster and subsequent installs are working fine.
Error message after cluster provisioning would be 
```
Error (exit code 1): You need to configure artifact storage. More information on how to do this can be found in the docs: https://argoproj.github.io/argo-workflows/configure-artifact-repository/.
```

fix: Argo ConfigMap and prepare 0.8.3 release

---

CHANGELOG.md
chart/infra-server/Chart.yaml

Bumping demo versions for ACS release 4.2.2

Bump demo versions to 4.2.2

---

chart/infra-server/static/workflow-openshift-multi.yaml

[ROX-20296](https://issues.redhat.com/browse/ROX-20296), ref: https://redhat-internal.slack.com/archives/CC5UHD0KA/p1699470694025049?thread_ts=1699452056.973829&cid=CC5UHD0KA
```
$ INFRA_TOKEN="$STAGE_INFRA_TOKEN" bin/infractl -k -e localhost:8443 create openshift-multi
ID: gj-11-08-12
```

chore: move openshift-multi to RH GCP

---

CHANGELOG.md
chart/infra-server/Chart.yaml
chart/infra-server/static/flavors.yaml
chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-4-perf-scale.yaml
chart/infra-server/static/workflow-openshift-4.yaml
chart/infra-server/templates/openshift-4/secrets.yaml

stackrox/stackrox CI uses`credentialsMode: Passthrough` to reduce the number of IAM policy bindings. Infra should default to provide the same type of cluster. This PR provides a parameter to override the default.
```
$ INFRA_TOKEN="$STAGE_INFRA_TOKEN" bin/infractl -k -e localhost:8443 create openshift-4
ID: gj-11-08-1
```
UI defaults for openshift-4-perf-scale: https://localhost:8443/cluster/gj-11-08-spotless-scissors-b
```
$ INFRA_TOKEN="$STAGE_INFRA_TOKEN" bin/infractl -k -e localhost:8443 create openshift-4-demo --arg credentials-mode=Mint
ID: gj-11-08-3
```

chore: match infra OCP credentialsMode with stackrox CI

---

server/server.go

Currently, the browser attempts to download the manifest in the background from the `BASE_URL/manifest.json`. 
It is then forwarded to `/login` and the SSO provider, which fails with 401. While a backoff seems to be implemented client-side, it is still a nuisance because it pollutes the network logs and uses unnecessary resources 🌍 🌳 . 
Example: 
This is the manifest: https://github.com/stackrox/infra/blob/master/ui/public/manifest.json

fix(ROX-20938): make PWA manifest accessible without authentication

---

CHANGELOG.md

Confirmed that with a 0.8.7 the `infractl get <cluster ID> --json` command still works (it will just not output parameters, no errors - yay to protobufs!). Tested against the PR cluster.
Confirmed also that 0.8.8 CLI will show the parameters for the same cluster as expected.

chore: prepare 0.8.8 release

---

.github/workflows/PR.yaml

Dependabot PR clusters can be short lived. Today I noticed:
```
infra-pr-1119 
infra-pr-1053 
infra-pr-1100 
infra-pr-1092 
infra-pr-1118 
infra-pr-1117 
infra-pr-1116 
infra-pr-1115 
infra-pr-1114 
infra-pr-1113 
infra-pr-1112 
infra-pr-1111 
infra-pr-1110 
infra-pr-1109 
infra-pr-1108 
infra-pr-1107 
```

fix(CI): limit the lifespan for dependabot PR clusters

---

.gitignore
.vscode/launch.json
Makefile
README.md
cmd/infra-server/main.go
scripts/local-dev/go.mod
scripts/local-dev/go.sum
scripts/local-dev/main.go
scripts/local-dev/prepare.sh
service/cli.go
service/package.go

See README for usage.
Please test it before approving!
You can use `gcloud container clusters get-credentials infra-pr-1104 --zone us-central1-a --project acs-team-temp-dev` to point to a cluster with workflow controller and secrets prepared.

feat: add debug prep scripts and configuration for server

---

chart/infra-server/static/flavors.yaml
chart/infra-server/static/workflow-demo.yaml
chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-rosa.yaml
chart/infra-server/static/workflow-osd-aws.yaml
chart/infra-server/static/workflow-osd-gcp.yaml
chart/infra-server/static/workflow-qa-demo.yaml

Related https://github.com/stackrox/automation-flavors/pull/181
Tested in PR cluster that provisioning works with default values and: 
- for demo flavors: `eu` and `us` zones
- for ROSA: `us-east-1` & `us-west-2` zones -> eu-central-1 did not have quota. Should anyone ever want to use that, we can address it then 🙃 
- for OSD: `us-east` variants.

ROX-15695: implement region&zone configuration for some more flavors

---

CHANGELOG.md
chart/infra-server/static/flavors.yaml

Fixes the new region and zone parameters and allows them to be optional. This caused a problem with the release automation: https://redhat-internal.slack.com/archives/CVANK5K5W/p1705510320169549
Apparently, you must specify non-optional values, even if we set a value in `flavors.yaml`: https://github.com/stackrox/infra/blob/blugo/fix-region-parameters/service/cluster/cluster.go#L834-L863
Before the changes in this PR:
```
❯ infractl -k -e localhost:8443 create qa-demo bl-1150-test --lifespan 2h --arg 'main-image=quay.io/rhacs-eng/main:4.3.4-rc.1,central-db-image=quay.io/rhacs-eng/central-db:4.3.4-rc.1'
NOTE: infractl no longer requires a NAME parameter when creating a cluster.
If ommitted a name will be generated using your infra user initials, a
short date and a counter for uniqueness. …
```

fix: region and zone parameters should be optional

---

.github/workflows/PR.yaml

Re: https://github.com/stackrox/automation-iac/pull/64. The new credential was added to GHA secrets including for dependabot.

chore(CI): use RH SA

---

.github/workflows/deploy.yaml

Per title. The replacement SA is in a new GHA secret. 
Tested with deployment to dev: https://github.com/stackrox/infra/actions/runs/8072643133
IaC PR: https://github.com/stackrox/automation-iac/pull/66

chore: use RH SA for gitops-deploy

---

.github/workflows/tag.yaml
CHANGELOG.md

This is similar to automation-flavors. 
I suggest to abandon the CHANGELOG.

ROX-22812: automatically bump the infra version on commit to master

---

cmd/infractl/cluster/create/command.go

This flag can be defined twice, when calling `infractl create qa-demo something-qa-demo`.
Breaking the loop after the first occurrence (which must be the flavor, because the `infractl create FLAVOR [NAME]`) fixes this issue.
Found during smoke testing https://github.com/stackrox/infra/actions/runs/8156066579/job/22295815499.
I will deploy the resulting release from master, as this is a user-facing bug (and blocks #1203 ).

fix: --rhacs flag can be redefined in qa-demo flavor

---

.github/workflows/deploy.yaml

Waiting for the infra-server image in the deploy workflow ensures that the helm upgrade will not fail because of missing images.

fix: wait for image in deploy.yaml

---

chart/infra-server/templates/deployment.yaml
config/config.go
server/server.go

Moved metrics to a different port, so they aren't world-readable anymore.
Verify with the cluster linked in the comment below:
* `kubectl port-forward deploy/infra-server-deployment -n infra 9101:9101`
* Access https://localhost:9101/metrics

fix(ROX-15587): expose metrics on different port to rest of server

---

chart/infra-server/static/workflow-openshift-multi.yaml

Two subsequent cluster creations failed due to 1h timeout. 
Doubling the timeout for the `create` phase should be sufficient.  
Context: https://redhat-internal.slack.com/archives/CMH5M8MHN/p1710418272486319

fix: Double OCP 3.11 create phase timeout

---

chart/infra-monitoring/values.yaml

Another tiny increment.
Proof:
```
$ kubectl get pvc -n monitoring
NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-stack-kube-prom-prometheus-db-prometheus-prometheus-stack-kube-prom-prometheus-0   Bound    pvc-fa75280f-e094-4318-a629-628196eb13a9   8Gi        RWO            standard-rwo   67m
```

ROX-15587: enable prometheus persistence

---

chart/infra-server/static/workflow-openshift-4-demo.yaml
chart/infra-server/static/workflow-openshift-4-perf-scale.yaml

https://github.com/stackrox/automation-flavors/pull/191 (and https://github.com/stackrox/infra/pull/1168) introduced a requirement to specify the cluster name in the `destroy` step of the `openshift-4-demo` and `openshift-4-perf-scale` flavors. I suspect since https://github.com/stackrox/infra/pull/1184 was merged, all `openshift-4-demo` clusters have been leaking.
These changes add the cluster name to the `destroy` step in the `openshift-4-demo` and `openshift-4-perf-scale` flavors.

fix: destroy openshift-4-demo & openshift-4-perf-scale clusters

---

chart/infra-server/templates/aws/secrets.yaml
cmd/infractl/cluster/utils/validate.go

osd-on-aws is getting these values from osd-access-secrets: https://github.com/stackrox/infra/blob/master/chart/infra-server/static/workflow-osd-aws.yaml#L62-L71

chore: remove unneeded secret values

---

chart/infra-server/static/workflow-demo.yaml
chart/infra-server/static/workflow-qa-demo.yaml

From experience with CI (and a recent infra flake) we known that quya.io pulls can be quite slow.

fix: extend deadline for roxctl pulls from quay.io

---

chart/infra-server/static/workflow-openshift-4-demo.yaml

fix: extend other deadlines for roxctl pulls from quay.io

---

Makefile

When multiple tags are associated with the current commit, the `TAGGED` in the Makefile will contain more than one tag. Any time we use this variable, we assume that there is only one tag.
These changes explicitly get the most recent tag and only one tag associated with the current commit.
Slack thread: https://redhat-internal.slack.com/archives/C04KV7S8KHV/p1713466775971019

fix: get only the most recent tag in Makefile

---

cmd/infractl/token/command.go

Many of our service account tokens have hyphens in the token name, which were generated before the validation changes. This PR allows us to renew those tokens

fix: allow hyphen in create token

---

chart/infra-server/templates/argo/secrets.yaml

Used in:
- Argo config for the artifacts destination:
https://github.com/stackrox/infra/blob/3e108306afcf0bed2ddf21a046e56cd74f31cee3/chart/infra-server/templates/argo/secrets.yaml#L15
- Signed URLs for artifacts download:
https://github.com/stackrox/infra/blob/3e108306afcf0bed2ddf21a046e56cd74f31cee3/signer/signer.go#L70
- The Infra server reads the artifacts to handle special tags for URL and connect string.
Requires https://github.com/stackrox/automation-iac/pull/117
- ~used `ENVIRONMENT=development make secrets-edit`~ this created an invalid secret
- used `ENVIRONMENT=development make secrets-download`
- and input from IaC:
- `terragrunt output -raw artifacts_sa_private_key_json`
- used `ENVIRONMENT=development make secrets-upload`
Try again.

ROX-22710: switch to new bucket

---

Makefile
scripts/deploy/secrets.sh

Changes the deploy script to use secrets from the RH GCP project. Testing detailed in https://github.com/stackrox/automation-iac/pull/121.

ROX-22599: Move secrets to RH GCP

---

chart/infra-server/templates/demo-certifier.yaml
scripts/deploy/helm.sh

Noticed two issues while [debugging](https://redhat-internal.slack.com/archives/CVANK5K5W/p1718622040012109) `demo` flavor:
- demo certifier for rox.systems did not complete: `flag provided but not defined: -dns-gcp-project`
- we were still using the secrets from the old project to deploy infra, even when the secrets management had already moved to the new project.

fix: use secrets from new project

---

auth/claimrule/claim_rule_test.go
auth/tokenizer.go
go.mod
go.sum

`github.com/dgrijalva/jwt-go` is old and archived in favor of `github.com/golang-jwt/jwt`
`gopkg.in/square/go-jose.v2` is old and archived in favor of `github.com/go-jose/go-jose`
Honestly wasn't sure which one to pick, so I opted for `go-jose` because it seemed like it had the nicer interface. The stackrox/stackrox repo also uses both, but mostly `go-jose` so that helps with this decision, too.
If anyone knows a good way to test this, please let me know

chore: converge on go-jose

---

cmd/infractl/cluster/list/command.go
cmd/infractl/cluster/list/fancy.go

I use a few shell aliases and functions to ease my interaction with infra-created clusters. In order to make it a little easier to process existing clusters (e.g. automatically passing the cluster name to other commands), I've added a 'quiet' flag to `infractl list`, which only prints the cluster ID (name.)
I've not modified the json output at all, since it didn't feel as appropriate, but can add quiet mode support to that if requested.
I'm also open to better name suggestions for the flag itself.

Adds quiet flag to infractl list

---

chart/infra-server/static/workflow-openshift-multi.yaml

Openshift 3.11 build is broken due to base image EOL. Instead of attempting to fix, we disable the image build in https://github.com/stackrox/automation-flavors/pull/250 and pin the flavor image version to the last known good version, with the intention of fixing this in https://issues.redhat.com/browse/ROX-25537, should the need to update the image flavor ever arise.

fix(ROX-25537): pin openshift-multi to known good version

---

.github/workflows/PR.yaml
.gitignore
auth/claimrule/claim_rule.go
auth/claimrule/claim_rule_test.go

This allows multiple (Rover) groups to be specified in the OIDC configuration.

ROX-27432: allow regex in authentication claimrules

---

chart/infra-server/Chart.yaml
chart/infra-server/static/workflow-aks.yaml
chart/infra-server/templates/azure/secrets.yaml

Attach `stackrox-infra` ACR to infra clusters.

ROX-21529: attach stackroxinfra container registry to AKS

---

.github/dependabot.yml
.github/workflows/auto-merge.yml

Enable full auto-merge for Dependabot PRs for 
- Go
- Docker
- GHA
- (not UI, fyi @stackrox/ui-dep-updaters )
I have checked the branch protection rules for `main`. It requires passing 
- lint
- unit test
- build
- e2e tests

fix(toil): enable more auto-merge for Dependabot

---

.github/workflows/build-and-push.yaml
Makefile
image/Dockerfile
ui/.npmrc

follow up from #1496 .
also used this PR to validate that the new UI is working.

chore(ui): remove unused .npmrc 

---

pkg/service/cluster/cluster.go
test/e2e/cluster/helpers.go
test/e2e/cluster/logs_test.go

Clusters on infra.rox.systems don't show logs anymore, because the naming scheme of the workflow pod has changed, example: https://infra.rox.systems/cluster/infra-pr-1519
This change must have been introduced in one of the Argo version bumps that we did last week. 
Instead of the `node.ID` (node of the workflow graph), the name now includes the template name of the stage before the random part:
|||
|--|--|
| `node.ID` | `infra-pr-1519-p2lf7-2787033289` |
| pod | `infra-pr-1519-p2lf7-create-2787033289` |
Validated in the PR cluster for all flavors and added a test.

fix(infractl logs): pod running workflow node contains stage name

---

ui/vite.config.ts

Autogenerated Vite configuration set the base URL for assets to `'.'`, which causes the bootstrap js/css path to be incorrect when visiting the app from anything other than the index. This removes that section of config, returning the path to its default base of `'/'`.
Tested by:
Visiting the build produced by this PR and verifying manually. 
Verified with a kubectl port forward against `infra-pr-1544` cluster. ✅

Use an absolute base url for asset paths

---

chart/infra-server/static/flavors.yaml

This is mostly due to the additional resources required by Scanner V4 being installed by default.

chore: add additional worker to the ocp flavors
